### ISSUE TITLE
To show ebblink public url directly in Ebblink app

### ISSUE THREAD

**Issue by riazhazan** [ebbapp/ebblinkSDK#1]
Ho can I deep link Ebblink URL to display it directly in Ebblink Application if the user has installed the Ebblink app in his device using objective C. Right now I am loading the url in a Webview which asks user to download the Ebblink application from appstore. Once he downloaded the app, i need to navigate the url directly into Ebblink App. Please advice

**Comment by pballart** [comment]
There are two ways of viewing a shared image using the SDK. The first one is using the SDK itself if you have the imageId and the password you can call a method and it will give you an image. The second option is if the user has the ebblink app downloaded you just open the publicLink url in safari and it will automatically deep link and open the image in ebblink. So I'd suggest using the UIApplication openURL method.
